.TH GROFF_MOVIE 7 "11 April 2013"
.SH NAME
groff_movie \- groff 'movie' macros to support generation of screenplays
.SH SYNOPSIS
.B groff -movie
[
.I files
\&... ]
.SH DESCRIPTION
.B movie
is a macro set for groff, designed to format screenplays for PostScript
output
.SH USAGE
All macro names should be on a line by themselves.
.IP A
Action
.IP C
Character name
.IP D
Dialogue
.IP P
Parenthetical
.IP S
Scene
.IP TI
Title
.IP ST
Subtitle
.IP STE
Subtitle ends

TI, ST and STE are required once each at the beginning of a screenplay.
All other macros are optional and may be used as often or as little
as required.
.SH AUTHOR
.B movie
was written by Zo\[char235] Blade <zoe@bytenoise.co.uk>.
